#!/usr/bin/env php
<?php

use Silex\Application;
use LExpress\Silex\ConsoleServiceProvider;
use Symfony\Component\Console\Command\Command;

require __DIR__.'/../vendor/autoload.php';
set_time_limit(0);

$app = new Application();
$app->register(new ConsoleServiceProvider());

$app['command.crash'] = $app->share(function () {
    $command = new Command('crash-test');

    $command->setCode(function () {
        throw new \RuntimeException('Crash success!');
    });

    return $command;
});

$app['console']->run();
