#!/usr/bin/env php
<?php

/*
 * This file is part of LExpress / ConsoleServiceProvider.
 *
 * (c) Groupe Express Roularta - Jérôme Tamarelle
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

use Silex\Application;
use LExpress\Silex\ConsoleServiceProvider;
use Symfony\Component\Console\Command\Command;

require __DIR__.'/../vendor/autoload.php';
set_time_limit(0);

$app = new Application();
$app->register(new ConsoleServiceProvider());

$app['command.crash'] = $app->share(function () {
    $command = new Command('crash-test');

    $command->setCode(function () {
        throw new \RuntimeException('Crash success!');
    });

    return $command;
});

$app['console']->run();
